#!/usr/bin/env bash

set -eu

# shellcheck disable=SC2034
VERSION="0.2.0"
SCRIPT_NAME=$(basename "$0")

# Export variables used by sourced lib files
export REPO_VERSION=""
export REPO_USER=""
export REPO_NAME=""
export USER_NAME=""
export USER_EMAIL=""
export ARCHITECTURE=""
export DEB_NAME=""
export DEBTEMP_DIR="$HOME/.cache/spt"
export PKG_DIR="$DEBTEMP_DIR/pkg"
export DEB_DIR="$DEBTEMP_DIR/deb"

readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}

# shellcheck disable=SC1091
{
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/utils.sh"
}

# shellcheck disable=SC1083
parser_definition() {
    setup REST help:usage abbr:true -- \
        "Usage: ${2##*/} [command] [options...] [arguments...]"
    msg -- '' 'Options:'
    disp :usage -h --help
    disp VERSION --version

    msg -- '' 'Commands: '
    msg -- 'Use command -h for a command help.'
    cmd create -- "Creates a pre-package"
    cmd open -- "Open the pre-package with VSCode"
    cmd generate -- "Generate a Debian package"
    cmd install -- "Install the local Debian package"
    cmd list -- "List cached packages"
    cmd clean -- "Clean the cache directory"

    msg -- '' "Examples:

Display the version:
    $SCRIPT_NAME --version
Display help:
    $SCRIPT_NAME -h | --help
Create a package:
    $SCRIPT_NAME create username/repo
"
}

eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

parser_definition_create() {
    setup REST plus:true help:usage abbr:true -- \
        "Usage: ${2##*/} create [options...] [arguments...]" ''

    msg -- 'Creates a pre-debian package.'

    flag CODE -c --code -- "Open the created pre-debian package with VSCode"
    flag YES -y --yes -- "Skip confirmation prompts"
    disp :usage -h --help

    msg -- '' "Examples:
Create a package:
    ${2##*/} create username/repo
Create and open in VSCode:
    ${2##*/} create -c username/repo
Skip confirmations:
    ${2##*/} create -y username/repo
"
}

parser_definition_generate() {
    setup REST plus:true help:usage abbr:true -- \
        "Usage: ${2##*/} generate [options...] [arguments...]" ''

    msg -- 'Generate a debian package.'

    flag DRYRUN -d --dry-run -- "Show what would be done without doing it"
    param OUTPUT -o --output -- "Output directory for .deb file (default: $DEB_DIR)"
    disp :usage -h --help

    msg -- '' "Examples:
Generate package:
    ${2##*/} generate
Dry run:
    ${2##*/} generate --dry-run
Custom output:
    ${2##*/} generate -o /tmp/packages
"
}

parser_definition_open() {
    setup REST plus:true help:usage abbr:true -- \
        "Usage: ${2##*/} open [options...]" ''

    msg -- 'Open the pre-package with VSCode.'

    disp :usage -h --help

    msg -- '' "Examples:
Open pre-package:
    ${2##*/} open
"
}

parser_definition_install() {
    setup REST plus:true help:usage abbr:true -- \
        "Usage: ${2##*/} install [options...] [arguments...]" ''

    msg -- 'Install the local debian package.'

    disp :usage -h --help

    msg -- '' "Examples:
Install package:
    ${2##*/} install
"
}

parser_definition_list() {
    setup REST plus:true help:usage abbr:true -- \
        "Usage: ${2##*/} list [options...]" ''

    msg -- 'List cached packages.'

    disp :usage -h --help
}

parser_definition_clean() {
    setup REST plus:true help:usage abbr:true -- \
        "Usage: ${2##*/} clean [options...]" ''

    msg -- 'Clean the cache directory.'

    flag FORCE -f --force -- "Force clean without confirmation"
    disp :usage -h --help

    msg -- '' "Examples:
Clean cache:
    ${2##*/} clean
Force clean:
    ${2##*/} clean -f
"
}

if [ $# -gt 0 ]; then
    cmd=$1
    shift
    case $cmd in
    create)
        eval "$(getoptions parser_definition_create parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/lib/create.sh"
        fn_create "$@"
        ;;
    generate)
        eval "$(getoptions parser_definition_generate parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/lib/generate.sh"
        fn_generate "$@"
        ;;
    open)
        eval "$(getoptions parser_definition_open parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/lib/open.sh"
        fn_open "$@"
        ;;
    install)
        eval "$(getoptions parser_definition_install parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/lib/install.sh"
        fn_install "$@"
        ;;
    list)
        eval "$(getoptions parser_definition_list parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/lib/list.sh"
        fn_list "$@"
        ;;
    clean)
        eval "$(getoptions parser_definition_clean parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/lib/clean.sh"
        fn_clean "$@"
        ;;
    --) ;; # no subcommand, arguments only
    esac
fi
